### ISSUE TITLE
An option to use native urls over proxy urls

### ISSUE THREAD

**Issue by brian6932** [singhkumarpratik/TMDB-Torrent-Movie-Database#4]
I mentioned this before in a closed issue: https://github.com/singhkumarpratik/TMDB-Torrent-Movie-Database/issues/1#issuecomment-667595202, but it looks to have gone unnoticed, so here I am again, there are many UserStyles, UserScripts, and extensions written for native urls which do not work on proxy urls, adding an option to use native urls would circumvent this issue and would be by far the simplest solution

**Comment by prxtiksingh** [comment]
Hi. I'm a little occupied with my personal work currently, but I would be happy to review your pull request if you can make the changes. The reason why proxy urls were used is because the original urls are banned by many ISPs.

Meanwhile, as an alternative, you can also simply fork the repo and replace proxy urls with the native urls.

**Comment by brian6932** [comment]
[I did that lol](https://github.com/brian6932/TMDB-Torrent-Movie-Database)
